Repository openshift/ci-operator, pull requests merged in 2018-09, with the labels that each got.

#123 Move JobSpec from steps to api so we can break up the steps package
  cmd/ci-operator/main.go
  pkg/api/job_spec.go
  pkg/steps/build_defaults.go
  pkg/steps/build_defaults_test.go
  pkg/steps/images_ready.go
  pkg/steps/input_image_tag.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/promote.go
  pkg/steps/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/test.go
  pkg/steps/write_params.go
Labels: approved, lgtm, size/L

#124 Move the build_defaults file to its own package
  cmd/ci-operator/main.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/promote.go
  pkg/steps/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/test.go
Labels: approved, lgtm, size/L

#127 Use headings for env in doc so they're linkable
  TEMPLATES.md
Labels: approved, lgtm, size/L

#129 Trim labels so they are validated
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/test.go
Labels: approved, lgtm, size/S

#132 Set the openshift source reference labels when building branches
  pkg/steps/project_image.go
Labels: approved, lgtm

#134 Clear id and ref if we don't set them ourselves
  pkg/steps/project_image.go
Labels: approved, lgtm

#138 Update ONBOARD.md example to YAML
  ONBOARD.md
Labels: approved, lgtm, size/M

#139 We were being too clever with rolling up errors
  pkg/steps/run.go
  pkg/steps/source.go
  pkg/steps/template.go
Labels: approved, lgtm, size/M

#120 Add custom base image option.
  ONBOARD.md
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/git_source.go
Labels: approved, lgtm, size/L

#146 Improve UX for job spec resolution
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#148 Move to using deployments for RPM serving
  pkg/defaults/defaults.go
  pkg/steps/rpm_server.go
Labels: approved, lgtm, size/M

#149 Optional images should be referencable by templates
  pkg/defaults/defaults.go
  pkg/steps/project_image.go
Labels: approved, lgtm, size/S

#151 Update CONFIGURATION.md for build_root
  CONFIGURATION.md
Labels: approved, lgtm, size/M

#152 Remove ability to override spec
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#154 remove test_base_image.
  CONFIGURATION.md
  ONBOARD.md
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  test/config.json
Labels: approved, lgtm, size/M

#155 Add git to the ci-operator image
  images/ci-operator/Dockerfile
Labels: approved, lgtm, size/XS

#125 Add test types
  ONBOARD.md
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
Labels: approved, lgtm, size/L

#156 Set GOPATH when cloning
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#157 Fix the project image key to match the documentation
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#159 Substitute targets that are covered by input ENV
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/input_env.go
  test/template.yaml
Labels: approved, lgtm, size/L

#143 Config validation updates.
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/defaults/defaults.go
Labels: approved, lgtm, size/XL

#161 Retry conflicts on promotion
  pkg/steps/promote.go
Labels: approved, lgtm, size/L

#162 ci-operator should expose RPM_REPO_<org>_<repo>
  TEMPLATES.md
  cmd/ci-operator/main.go
  pkg/steps/rpm_server.go
Labels: approved, lgtm, size/S
