Repository openshift/ci-operator, pull requests merged in 2018-06, with the labels that each got.

#22 Add a promotion definition that will copy pipeline tags out
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/api/types.go
  pkg/steps/build_defaults.go
  pkg/steps/promote.go
Labels: size/L

#23 Improvements to support multi-stage builds and cleaner go The context_dir and docker path don't always align. Add dockerfile_path and pass that to the build. Also, for multistage builds and reuse of previous artifacts add a new `inputs` map that creates build api ImageSource items from an existing pipeline image ref. Example:
  pkg/api/types.go
  pkg/steps/build_defaults.go
  pkg/steps/job_spec.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
Labels: size/L

#24 Improve debugging of what steps are being run
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/steps/input_image_tag.go
  pkg/steps/release_images.go
  pkg/steps/run.go
Labels: size/L

#25 Inject clonerefs into the source builds
  pkg/api/types.go
  pkg/steps/build_defaults.go
  pkg/steps/input_image_tag.go
  pkg/steps/source.go
Labels: lgtm, size/L

#27 Support additional image promotions during promote
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/api/types.go
  pkg/steps/build_defaults_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/output_image_tag.go
  pkg/steps/promote.go
  pkg/steps/release_images.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
Labels: size/L

#29 Perform a submodule init on the cloned code
  pkg/steps/source.go
Labels: size/XS

#30 Print job spec info at startup
  cmd/ci-operator/main.go
Labels: size/S

#31 Dry run now defaults to false
  cmd/ci-operator/main.go
Labels: lgtm, size/XS

#32 Use a shorter tag println to avoid repetition
  pkg/steps/output_image_tag.go
Labels: lgtm, size/XS

#34 RPM_REPO should be a URL, not a bare host
  pkg/steps/rpm_server.go
Labels: lgtm, size/XS

#35 Use a multithreaded python server to serve RPMs
  pkg/steps/rpm_server.go
Labels: lgtm, size/M

#36 Expose 'src' as LOCAL_IMAGE_SRC for use in template jobs
  pkg/steps/source.go
Labels: lgtm, size/S

#33 Add an `optional` field to project images and output images
  cmd/ci-operator/main.go
  pkg/api/types.go
  pkg/steps/build_defaults.go
Labels: lgtm, size/M

#37 Give the RPM server a realistic cpu/mem requests
  pkg/steps/rpm_server.go
Labels: lgtm, size/XS

#38 Generate JUnit reports when --artifact-dir is specified
  cmd/ci-operator/main.go
  pkg/junit/types.go
  pkg/steps/run.go
  pkg/steps/run_test.go
Labels: lgtm, size/L

#39 If the pod status is cleared on a terminal pod, don't loop forever
  pkg/steps/template.go
Labels: lgtm, size/S

#40 Print more human readable descriptions into the junit
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/steps/images_ready.go
  pkg/steps/input_image_tag.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/promote.go
  pkg/steps/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/test.go
  pkg/steps/write_params.go
Labels: lgtm, size/M

#41 When pods and builds fail, report more information about them
  pkg/steps/run.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/test.go
Labels: lgtm, size/M

#42 Try harder to cleanup the artifact side car
  pkg/steps/artifacts.go
Labels: lgtm, size/S
