Repository openshift/ci-operator, pull requests merged in 2018-11, with the labels that each got.

#196 build: Clear more default annotations when we build images
  pkg/steps/project_image.go
Labels: approved, lgtm, size/S

#193 Log containers output to artifacts.
  TEMPLATES.md
  pkg/steps/template.go
  pkg/steps/test.go
Labels: approved, lgtm, size/M

#198 pkg/steps/template: Return pod list from waitForPodCompletionOrTimeout
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#199 add openshift_installer_src test configuration
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#201 Fix error messages.
  pkg/steps/template.go
  pkg/steps/test.go
Labels: approved, lgtm, size/XS

#204 validation: 'cluster' is not a required field
  pkg/api/config.go
Labels: approved, lgtm, size/XS

#205 Revert container output logging until it can be fixed
  TEMPLATES.md
  pkg/steps/template.go
  pkg/steps/test.go
Labels: approved, lgtm, size/L

#207 Add more profiles for openshift-ansible 4.0 testing
  pkg/api/types.go
Labels: approved, lgtm, size/S

#208 Add new 4.0 profiles in validateClusterProfile
  pkg/api/config.go
Labels: approved, lgtm, size/XS

#206 Container output to artifacts
  TEMPLATES.md
  pkg/steps/artifacts.go
Labels: approved, lgtm, size/M

#210 Add a new test type for openshift-ansible 4.0 install
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#211 Update documentation for `openshift_ansible_40` test
  CONFIGURATION.md
Labels: approved, lgtm, size/XS

#212 add gcp cluster profiles for logging
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#216 Fix a possible deadlock in waitForCompletionOrTimeout
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#218 Clarify onboarding instructions
  ONBOARD.md
Labels: approved, lgtm, size/S

#213 Unit tests for some more straightforward steps
  pkg/steps/input_env_test.go
  pkg/steps/template_test.go
  pkg/steps/testing.go
  pkg/steps/write_params_test.go
Labels: approved, lgtm, size/L

#220 Fix more deadlock opportunities
  pkg/steps/rpm_server.go
  pkg/steps/source.go
Labels: approved, lgtm, size/M

#221 Unit tests ImageReady step
  pkg/defaults/defaults.go
  pkg/steps/images_ready.go
  pkg/steps/images_ready_test.go
Labels: approved, lgtm, size/M
