Repository openshift/ci-operator, pull requests merged in 2018-07, with the labels that each got.

#43 Allow a project image build to override the "src" injection
  pkg/steps/project_image.go
  pkg/steps/source.go
Labels: lgtm, size/S

#44 Allow promotion to be defaulted when non-nil
  pkg/steps/build_defaults.go
  pkg/steps/promote.go
Labels: lgtm, size/XS

#45 Don't write a file into the working dir during clone
  pkg/steps/source.go
Labels: lgtm, size/XS

#47 git-ref should override JOB_SPEC refs field
  cmd/ci-operator/main.go
Labels: lgtm

#50 Spread RPM server over two servers to ensure availability
  pkg/steps/rpm_server.go
Labels: lgtm, size/XS

#51 Make the project go-gettable
  doc.go
Labels: lgtm, size/XS, ¯\_(ツ)_/¯

#53 add relevant vscode metadata to gitignore
  .gitignore
Labels: lgtm, size/XS

#49 Fix error messages on client creation failures
  cmd/ci-operator/main.go
Labels: lgtm, size/XS

#58 Use a job for idle cleanup so that pod eviction doesn't orphan namespaces
  cmd/ci-operator/main.go
Labels: lgtm, size/M

#59 Don't tear down namespace when interrupted
  cmd/ci-operator/main.go
Labels: lgtm, size/S

#60 Increase namespace default teardown to 1 hour
  cmd/ci-operator/main.go
Labels: lgtm

#61 When importing images from the same cluster, use refs
  pkg/steps/input_image_tag.go
  pkg/steps/release_images.go
Labels: lgtm, size/XS

#66 Wait for RPM server URL to be reachable before continuing
  pkg/steps/rpm_server.go
Labels: approved, lgtm, size/M

#67 RPM server service should only use some labels
  pkg/steps/rpm_server.go
Labels: approved, lgtm, size/XS

#69 Print information about template if deletion takes longer than 30 minutes
  pkg/steps/template.go
Labels: approved, lgtm, size/XS

#57 Add README, onboarding and config reference docs
  ONBOARD.md
  README.md
Labels: approved, lgtm, size/L
