Repository openshift/ci-operator, pull requests merged in 2018-08, with the labels that each got.

#72 Add a CONTRIBUTORS.md file about contribution to ci-operator
  CONTRIBUTORS.md
Labels: approved, lgtm, size/M

#73 --git-ref: Fail fast when ref does not resolve
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#74 Make -h and --help behave equally
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#80 Create rolebinding for the PR author.
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#75 Use the NS TTL Controller instead of cleanup pod
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/L

#85 Bind namespace admin to author, not cluster admin
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#86 Add more contexts to errors
  cmd/ci-operator/main.go
  pkg/steps/artifacts.go
  pkg/steps/build_defaults.go
  pkg/steps/input_image_tag.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/release_images.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/test.go
  pkg/steps/write_params.go
Labels: approved, lgtm, size/L

#87 Retry namespace update for TTL labels
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#82 Label all pods we create with the ProwJobID for artifacts
  pkg/steps/job_spec.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/test.go
Labels: approved, lgtm, size/M

#89 Fix a regression caused by error checking
  pkg/steps/output_image_tag.go
Labels: approved, lgtm, size/S

#90 ns ttl update retry.
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#91 Warn instead of fail when user doesn't have namespace update permission
  cmd/ci-operator/main.go
  pkg/steps/release_images.go
Labels: approved, lgtm, size/M

#94 Bind the admin clusterrole in test namespaces
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#96 Add an image build
  images/ci-operator/Dockerfile
Labels: approved, lgtm, size/XS

#97 Add a make target to install
  Makefile
Labels: approved, lgtm, size/XS

#95 Add documentaton for build/release env builds
  ONBOARD.md
Labels: approved, lgtm, size/M

#98 Allow release tag configuration to be omitted for unrelated repos
  pkg/api/types.go
  pkg/steps/build_defaults.go
Labels: approved, lgtm, size/M

#101 Add an entrypoint to validate configuration
  Makefile
  ci-operator-checkconfig
  cmd/ci-operator-checkconfig/main.go
  images/ci-operator-checkconfig/Dockerfile
Labels: approved, lgtm, size/M

#99 Update job config directions in the readme
  ONBOARD.md
Labels: approved, lgtm, size/XS

#103 When no release configuration is in place, have a shim prereq
  pkg/steps/build_defaults.go
  pkg/steps/release_images.go
Labels: approved, lgtm, size/M

#104 Skuznets/fix committed binary
  .gitignore
  ci-operator-checkconfig
Labels: approved, lgtm, size/XS

#106 Fix .gitignore to exclude only binaries
  .gitignore
Labels: approved, lgtm, size/XS

#107 Ensure gofmt
  Makefile
  doc.go
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#102 Ensure target imagestream exists before promoting
  pkg/steps/promote.go
Labels: approved, lgtm, size/S

#105 Add documentation for the CI Operator configuration
  CONFIGURATION.md
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#110 Direct users to ci-operator-prowgen in ONBOARD.md
  ONBOARD.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#100 Send events with some usefull information.
  cmd/ci-operator/main.go
  vendor/github.com/davecgh/go-spew/.gitignore
  vendor/github.com/davecgh/go-spew/.travis.yml
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/README.md
  vendor/github.com/davecgh/go-spew/cov_report.sh
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/common_test.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/dump_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
  vendor/github.com/davecgh/go-spew/spew/dumpnocgo_test.go
  vendor/github.com/davecgh/go-spew/spew/example_test.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/format_test.go
  vendor/github.com/davecgh/go-spew/spew/internal_test.go
  vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/davecgh/go-spew/spew/spew_test.go
  vendor/github.com/davecgh/go-spew/spew/testdata/dumpcgo.go
  vendor/github.com/davecgh/go-spew/test_coverage.txt
  vendor/github.com/golang/groupcache/.gitignore
  vendor/github.com/golang/groupcache/.travis.yml
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/README.md
  vendor/github.com/golang/groupcache/byteview.go
  vendor/github.com/golang/groupcache/byteview_test.go
  vendor/github.com/golang/groupcache/consistenthash/consistenthash.go
  vendor/github.com/golang/groupcache/consistenthash/consistenthash_test.go
  vendor/github.com/golang/groupcache/groupcache.go
  vendor/github.com/golang/groupcache/groupcache_test.go
  vendor/github.com/golang/groupcache/groupcachepb/groupcache.pb.go
  vendor/github.com/golang/groupcache/groupcachepb/groupcache.proto
  vendor/github.com/golang/groupcache/http.go
  vendor/github.com/golang/groupcache/http_test.go
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/github.com/golang/groupcache/lru/lru_test.go
  vendor/github.com/golang/groupcache/peers.go
  vendor/github.com/golang/groupcache/singleflight/singleflight.go
  vendor/github.com/golang/groupcache/singleflight/singleflight_test.go
  vendor/github.com/golang/groupcache/sinks.go
  vendor/github.com/golang/groupcache/testpb/test.pb.go
  vendor/github.com/golang/groupcache/testpb/test.proto
Labels: approved, lgtm, size/XXL

#112 Allow local image lookups on promoted images
  pkg/steps/promote.go
Labels: approved, lgtm, size/XS

#111 Add documentation on the use of template steps
  TEMPLATES.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L, ¯\_(ツ)_/¯

#114 Get rid of two lint warnings
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#113 Validate ci-operator configuration beyond "correct JSON"
  cmd/ci-operator-checkconfig/main.go
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/api/config_test.go
  test/config.json
Labels: approved, lgtm, size/M

#115 Add promotion default doc
  CONFIGURATION.md
Labels: approved, lgtm, size/XS

#116 Events should not be logged
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#117 Correctly return error when creating build
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#119 fix vetting in makefile
  Makefile
Labels: approved, lgtm, size/XS

#121 Change the configuration file format to YAML
  CONFIGURATION.md
  ONBOARD.md
  README.md
  cmd/ci-operator-checkconfig/main.go
  cmd/ci-operator/main.go
  glide.yaml
  pkg/api/types_test.go
  test/config.json
Labels: approved, lgtm, size/L
