Repository openshift/ci-operator, pull requests merged in 2018-10, with the labels that each got.

#168 Add DPTP to owners
  OWNERS
Labels: approved, lgtm, size/XS

#169 Ensure e2e tests have correct release
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm, size/M

#166 validations doc
  VALIDATIONS.md
Labels: approved, lgtm, size/M

#165 Document new test types
  CONFIGURATION.md
Labels: approved, lgtm, size/M

#173 Use cluster profile instead of target cloud
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
Labels: approved, lgtm, size/M

#172 Write an architectural overview of ci-operator
  ARCHITECTURE.md
  README.md
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/L

#177 add active annotation
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#178 Update tests documentation
  CONFIGURATION.md
Labels: approved, lgtm, size/S

#179 Wait until pods are deleted in the initial cleanup
  pkg/steps/template.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#180 Handle problems when cleaning up leftover pods
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#181 Remove the deprecated `from` field from tests
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/test.go
Labels: approved, lgtm, size/M

#182 Add better validation for resource requests and limits
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm, size/L

#176 Add new cluster profiles - aws-gluster and gcp-logging
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/M

#184 Add annotation to output logs for all containers.
  TEMPLATES.md
  pkg/steps/template.go
Labels: approved, lgtm, size/M

#190 Add `--as` option for impersonating users
  cmd/ci-operator/main.go
Labels: approved, lgtm

#189 output logs containerwise.
  TEMPLATES.md
  pkg/steps/template.go
Labels: approved, lgtm, size/M

#192 remove deprecated annotation
  TEMPLATES.md
  pkg/steps/template.go
Labels: approved, lgtm, size/S
