Repository openshift/ci-operator, pull requests merged in 2018-12, with the labels that each got.

#225 Move the real clonerefs file, not the symlink
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm, size/XS

#230 If artifacts are requested, write metadata.json as gubernator expects
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#233 Don't double print "wait for completion" in pod errors
  pkg/steps/template.go
  pkg/steps/test.go
Labels: approved, lgtm, size/XS

#232 Usability improvements to validation for iteratively building a config.yaml
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/template.go
  test/config.yaml
  test/template.yaml
Labels: approved, lgtm, size/L

#235 The build api reports failure before log snippet
  pkg/steps/source.go
Labels: approved, lgtm, size/M

#219 Unit tests for test.go step
  Makefile
  pkg/steps/images_ready_test.go
  pkg/steps/input_env_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/testing.go
  pkg/steps/write_params_test.go
Labels: approved, lgtm, size/L
