Repository openshift/ci-operator, pull requests merged in 2019-03, with the labels that each got.

#282 Move release related code into a consistent spot
  pkg/api/parameters.go
  pkg/api/parameters_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/template.go
  pkg/steps/write_params.go
  pkg/steps/write_params_test.go
Labels: approved, lgtm, size/L

#283 Remove support for release configurations not in a single stream
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm, size/L

#285 Revert "Remove support for release configurations not in a single stream"
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm, size/L

#286 Remove support for release configurations not in a single stream
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm, size/L

#278 Require full branch name with --git-ref
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#289 Add trailing slash to baserepo, some yum-utils complain
  pkg/steps/rpm_injection.go
Labels: approved, lgtm, size/XS

#284 Create an initial release payload as `release:initial`
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm, size/L

#290 Revert "Merge pull request #284 from smarterclayton/build_initial"
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm, size/L

#291 Create an initial release payload as `release:initial`
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm, size/L

#287 Default `stable` image stream from RELEASE_IMAGE_LATEST
  pkg/steps/artifacts.go
  pkg/steps/pod.go
  pkg/steps/release/create_release.go
  pkg/steps/template.go
Labels: approved, lgtm, size/L

#292 api: Update the installer job to signal this is an upgrade
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#288 Implement a Golang cluster installer job that hides the template
  ARCHITECTURE.md
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/api/parameters.go
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/clusterinstall/template.go
  pkg/steps/images_ready.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
  pkg/steps/template.go
Labels: approved, lgtm, size/XL

#294 If no refs are provided, we can't build source, omit from graph
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/defaults/defaults.go
Labels: approved, lgtm, size/M

#295 Fix race when importing the release image stream
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/release/create_release.go
  pkg/steps/template.go
Labels: approved, lgtm, size/M

#296 Include binary size and binary modification date in input hash
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#297 RELEASE_IMAGE_INITIAL on a PR is based on stable, not stable-initial
  pkg/steps/release/create_release.go
Labels: approved, lgtm, size/XS

#298 Retry more infrastructure-related build failures
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#299 Use UID precondition to prevent races with other ci-operators
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#300 Convert secrets with specific shapes into pull secrets
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#302 Attempt to write a JUnit if we don't start running the graph
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#279 add abiility to dump openshift docker build strategy logs even if bui…
  pkg/defaults/defaults.go
  pkg/steps/artifacts.go
  pkg/steps/git_source.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
Labels: approved, lgtm, size/M

#303 shorten directory name for successful build log artifacts
  pkg/steps/artifacts.go
Labels: approved, lgtm, size/XS

#304 Add openshift_installer_upi test for UPI flow
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
  pkg/load/load_test.go
Labels: approved, lgtm, size/S

#305 Add vsphere profile
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#301 Add prepublish raw_step config option to publish images from PRs
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/image_stream_util.go
  pkg/steps/output_image_tag.go
  pkg/steps/pre_publish_images.go
  pkg/steps/pre_publish_images_test.go
  pkg/steps/testing.go
Labels: approved, lgtm, size/L

#306 Revert "Merge pull request #301 from chancez/pre_publish"
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/image_stream_util.go
  pkg/steps/output_image_tag.go
  pkg/steps/pre_publish_images.go
  pkg/steps/pre_publish_images_test.go
  pkg/steps/testing.go
Labels: approved, lgtm, size/L
