Repository openshift/ci-operator, pull requests merged in 2019-04, with the labels that each got.

#307 Update cluster install template
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/XS

#308 Update output_image_tag_step tests to test again pre-existing imagestreamtag
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/testing.go
Labels: approved, lgtm, size/L

#310 RetryOnConflict update against ImageStreamTags in output_image_tag_step
  pkg/steps/output_image_tag.go
Labels: approved, lgtm, size/S

#315 Improve build retry by ensuring cleanup succeeds
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#312 Make input hash independent on input ordering
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#313 Allow disabling promotion step via config
  pkg/api/types.go
  pkg/steps/release/promote.go
Labels: approved, lgtm, size/S

#316 Bump log level on builds
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#317 Look for likely infrastructure errors in the log snippet
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#318 Revert "Merge pull request #316 from stevekuznetsov/skuznets/loglevel"
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#319 only retry terminated builds
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#321 grab authors before jobspec manipulation
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#322 grab authors fix
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#311 Add prepublish raw_step config option to publish images from PRs
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/image_stream_util.go
  pkg/steps/images_ready.go
  pkg/steps/images_ready_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/pre_publish_images.go
  pkg/steps/pre_publish_images_test.go
Labels: approved, lgtm, size/XL

#323 Revert "Merge pull request #311 from chancez/pre_publish4"
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/image_stream_util.go
  pkg/steps/images_ready.go
  pkg/steps/images_ready_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/pre_publish_images.go
  pkg/steps/pre_publish_images_test.go
Labels: approved, lgtm, size/XL

#326 Always print the step that returns an error
  pkg/steps/run.go
Labels: approved, lgtm, size/XS

#327 Ignore if image tag already exists in output_image_tag step
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
Labels: approved, lgtm, size/M

#330 Restore force deletion of tag in outputImageTagStep
  pkg/steps/output_image_tag.go
Labels: approved, lgtm, size/XS

#331 Retry tagging the cli image from release import a few times
  pkg/steps/release/create_release.go
Labels: approved, lgtm, size/S

#332 Attempt to save current namespace resources to artifacts during exit
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#334 Add type for console tests
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/M

#335 Fix a copy artifact in CONFIGURATION.md
  CONFIGURATION.md
Labels: approved, lgtm, size/XS

#336 Importing release images can sometimes fail due to registry errors
  ARCHITECTURE.md
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm, size/M
