Repository openshift/ci-operator, pull requests merged in 2019-06, with the labels that each got.

#354 Sentry: Make fingerprints from sanitized error messages
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
Labels: approved, lgtm, size/L

#355 Sanitize UUIDs from Sentry fingerprints
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
Labels: approved, lgtm, size/S

#356 Merge Makefile with ci-operator-prowgen
  Makefile
Labels: approved, lgtm, size/M

#357 Remove old make target
  Makefile
Labels: approved, lgtm, size/XS

#358 template: extend timeout in waitForPodDeletion
  pkg/steps/template.go
Labels: approved, lgtm, size/XS

#359 Add link to openshift/ci-tools
  README.md
Labels: approved, lgtm, size/XS
