Repository openshift/ci-operator, pull requests merged in 2019-05, with the labels that each got.

#339 pkg/steps/clusterinstall/template: Update to pull in openshift/release changes
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/M

#340 Bug 1705243: Two PR jobs can race creating an image stream tag
  pkg/steps/output_image_tag.go
  test/testdata/copy_input_tag_to_output.yaml
Labels: approved, lgtm, size/M

#341 Small doc update
  ONBOARD.md
Labels: approved, lgtm, size/S

#342 Retry builds on evictions of build pod
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#345 Add hongkailiu to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#346 Report more failures to Sentry
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#347 Remove fake option validation code
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
Labels: approved, lgtm, size/M

#349 Allow the upgrade template to accept options as env
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/XS

#348 Make artifacts container survive longer after signal
  pkg/steps/artifacts.go
Labels: approved, lgtm, size/XS

#350 Add OWNERS for built-in templates
  pkg/steps/clusterinstall/OWNERS
Labels: approved, lgtm, size/S

#351 Improve messaging when pod is deleted while ci-op waits on it
  pkg/steps/template.go
Labels: approved, lgtm, size/XS

#352 *: add azure4 as a known cluster profile
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/XS
