Repository openshift/ci-operator, pull requests merged in 2019-02, with the labels that each got.

#255 test: Add an optional flag to the api for cluster tests
  CONFIGURATION.md
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#256 Revert "test: Add an optional flag to the api for cluster tests"
  CONFIGURATION.md
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#257 When multiple containers report unit status, don't overlap time
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
Labels: approved, lgtm, size/L

#253 test step secret inject
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
Labels: approved, lgtm, size/L

#263 api: Support a `memory_backed_volume` for tests that need fast IO
  CONFIGURATION.md
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
Labels: approved, lgtm, size/L

#267 Retry promotion longer
  pkg/steps/promote.go
Labels: approved, lgtm, size/S

#268 Avoid touching files already in the src image and causing a copy up
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#269 Correctly handle empty input on source when nothing has to be changed
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#270 We need to be able to run tests against many releases
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm, size/XS

#266 If cancelled, promotion was still being invoked
  pkg/steps/run.go
Labels: approved, lgtm, size/XS

#272 Disable defaulting on promotion
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
Labels: approved, lgtm, size/S

#260 Support extra_refs being passed to jobs and into src build
  cmd/ci-operator/main.go
  pkg/api/job_spec.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/git_source.go
  pkg/steps/project_image.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
Labels: approved, lgtm, size/L

#275 Prevent panic in periodic job with no pull requests
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#273 base: Allow base_images to be defaulted from tag_specification
  CONFIGURATION.md
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#277 Update serialization code
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/source.go
Labels: approved, lgtm, size/XL

#281 Make canonical go repository omitempty
  pkg/api/types.go
Labels: approved, lgtm, size/XS
