Repository openshift/ci-operator, pull requests merged in 2019-01, with the labels that each got.

#226 Tests for the OutputImageTag step
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/testing.go
Labels: approved, lgtm, size/L

#240 Recreate any OOMKilled build that already exists from previous runs.
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#246 Reverse order of PR link in namespace description
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#248 Update the location of the clonerefs file
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm, size/XS

#247 Allow pods to declare that they want one junit per container, instead of pod
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/pod.go
  pkg/steps/run.go
  pkg/steps/template.go
  test/template.yaml
Labels: approved, lgtm, size/L

#251 Ensure the release-latest pod gets created with requests
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
Labels: approved, lgtm, size/S

#252 Artifacts container is not always being shut down
  pkg/steps/artifacts.go
  pkg/steps/pod.go
Labels: approved, lgtm, size/S

#254 Allow images to be excluded from promotion, no matter what
  CONFIGURATION.md
  pkg/api/types.go
  pkg/steps/promote.go
Labels: approved, lgtm, size/S
